name: Dotnet

on:
  push:
    paths:
    - '.github/workflows/dotnet.yml'


jobs:
  windows:
    name: test dotnet
    runs-on: windows-latest 
    steps:
    - uses: actions/setup-dotnet@v1
      with: 
        dotnet-version: '4.6.2'
