name: If
on:
  push:
    paths:
    - '.github/workflows/if.yml'
  
env:
  this: false


jobs:
  test-if:
    runs-on: ubuntu-latest
    name: Test how to run an if in a job
    steps:
    - name: Yes
      run: |
        echo "Checking if we should lint"
        if [ "${{ env.this }}" = "false" ]; then
          echo "Not linting"
          exit 0
        fi
        echo "Linting!"
        exit 1
