name: If
on:
  push
  
env:
  this: false


jobs:
  test-if:
    runs-on: ubuntu-linux
    name: Test how to run an if in a job
    steps:
    - name: Yes
      run: |
        if [ ! ${{env.this}} ]; then
          echo "Not linting"
          exit 0
        fi
        echo "Linting!"
        exit 1
