name: Semver Bump

on:
  push:
    branches:
      - master

jobs:
  npm_audit:
    name: dependency audit
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: npm audit
      run: |
        npm audit

  tag:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@master
      env:
        DEFAULT_BUMP: patch
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        REPO_OWNER: sjauld
