name: Semver Bump

on:
  push:
    branches:
      - master

jobs:
  tag:
    name: bump semver
    runs-on: ubuntu latest
    steps:
    - uses: actions/checkout@v1
    - name: hello world
      run: |
        echo "Hello world"

    - name: bump semver
      run: |
        # if we have a blank tag, get all commits
        if [ -z "$t" ]
        then
            log=$(git log --pretty=oneline)
            t=0.0.0
        # otherwise, get commits since last tag
        else
            log=$(git log $t..HEAD --pretty=oneline)
        fi

        # supports #major, #minor, #patch (default 'patch')
        case "$log" in
            *#major* ) new=$(semver bump major $t);;
            *#minor* ) new=$(semver bump minor $t);;
            * ) new=$(semver bump patch $t);;
        esac
